name: Build on PR

on:
  pull_request:
    branches: [ "staging" ]
env:
  CI: ${{ secrets.CI }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run build